project:
  type: book
  output-dir: docs


book:
  title: "process-models-workshop"
  author: "The RoLE Team"
  date: "5/2/2023"
  chapters:
    - index.qmd
    - motivation.qmd
    - intro_to_role.qmd
    - how_role_works.qmd
    - getting_started.qmd
    - exploring_theory.qmd
    - inference_intro.qmd
    - inference_demo.qmd
    - reproducibility.qmd
    - wrapup.qmd
comments:
  hypothesis: true


bibliography: references.bib


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



