# Getting started: roleR

## Key questions

1. How do I set up and run a RoLE model in R?
1. How do I access and visualize the results of a RoLE simulation?
1. How can I store the outputs of a RoLE model?

## Lesson objectives

After this lesson, learners should be able to...

1. Use roleR to run a basic RoLE model.
1. Extract summary statistics from a RolE model, plot them, and relate the visuals to ecological/evolutionary processes.
1. Save RoLE models to disc.

## Planned exercises

* Code-along demo
* Experimentation time (set a challenge and report back?)

## Supporting materials

_Describe, and where possible link to, lesson materials that will be needed for this section of the workshop. These could include code for live coding, code documentation, book chapters, videos/animations, etc._

_For bonus points organize these according to whether they already exist or we need to create them!_

### Extant

### To create

* Relevant chapters of user guide.

## Key points

_List 1-3 key takeaways from this section of the workshop._