# Introduction

## Workshop outline

| Time | Day 1 | Day 2 |
|------|-------|-------|
| 9-9:30 | Introductions and workshop overview | Review of previous days topics |
| 9:30-10:30 | Theory/conceptual motivation for process models | Overview of simulation-based machine learning |
| 10:30-10:45 | Coffee Break | Coffee Break |
| 10:45-12 | Introduction to RoLE | Machine learning inference with RoLE simulations |
| 12-1 | Lunch Break | Lunch Break |
| 1-2:30 | Getting started running simulations with RoLE | Reproducibility (sharing and archiving) |
| 2:30-2:45 | Coffee Break | Coffee Break | 
| 2:45-4:00 | Using RoLE to develop and test theoretical intuition | Wrap-up and Feedback Session |


This is a quarto book project for creating materials for the second half of the MDBD workshop.

There is a list of planned sections in the "List of sections" chapter.

To add a new section, start from the "Template section". Open `template_section.qmd`, save-as, and populate it; then add it to the list of sections in `_quarto.yml`.

To update the Pages site, run `quarto render` from a local terminal. This will render the files to the `docs` directory. Then push, and GitHub pages will serve the site from `docs`. 
