# Introduction to the RoLE Model

## Key questions

1. What is the RoLE Model?
1. What are some of the possible applications of the RoLE Model?
1. How do I learn more?

## Lesson objectives

After this lesson, learners should be able to...

1. Situate RoLE in the wider process modeling state space.
1. Describe the (high-level) concept for RoLE.
1. Formulate scientific questions and decide if/how RoLE can be used to explore them.

## Planned exercises

1. Lecture: [Process-based modeling with the Rules of Life Engine (RoLE) Model](https://docs.google.com/presentation/d/1vLtGAnmaXSjEV05VTw9TpgjvN0rbBeyjc5TObPY-SFc/edit#slide=id.g437f980ed7_0_25)
1. Hands-on: Exploring RoLE model behavior with the RoLE-Shiny app

## Supporting materials

_Describe, and where possible link to, lesson materials that will be needed for this section of the workshop. These could include code for live coding, code documentation, book chapters, videos/animations, etc._

_For bonus points organize these according to whether they already exist or we need to create them!_

### Extant

### To create

## Key points

_List 1-3 key takeaways from this section of the workshop._
