  output-dir: docs
# Introduction to the MESS Model

## Key questions

1. What is the MESS Model?
1. What are some of the possible applications of the RoLE Model?
1. How do I learn more?

## Lesson objectives

After this lesson, learners should be able to...

1. Situate RoLE in the wider process modeling state space.
1. Describe the (high-level) concept for RoLE.
1. Formulate scientific questions and decide if/how RoLE can be used to explore them.

## Planned exercises

1. Lecture: [Process-based modeling with the Rules of Life Engine (RoLE) Model](https://docs.google.com/presentation/d/1vLtGAnmaXSjEV05VTw9TpgjvN0rbBeyjc5TObPY-SFc/edit#slide=id.g437f980ed7_0_25)
1. Hands-on: Exploring RoLE model behavior with the RoLE-Shiny app

## Supporting materials

_Describe, and where possible link to, lesson materials that will be needed for this section of the workshop. These could include code for live coding, code documentation, book chapters, videos/animations, etc._

_For bonus points organize these according to whether they already exist or we need to create them!_

### Extant

### To create

## Key points

_List 1-3 key takeaways from this section of the workshop._

# Getting started: roleR

## Key questions

1. How do I set up and run a RoLE model in R?
1. What are the inputs and outputs of a RoLE model?
1. What happens when a RoLE model runs?
1. How do I access and visualize the results of a RoLE simulation?
1. How can I store the outputs of a RoLE model?

## Lesson objectives

After this lesson, learners should be able to...

1. Describe the structure of a RoLE model.
1. Describe the rules of a RoLE simulation.
1. Describe the outputs of a RoLE model and what they say about the system.
1. Use roleR to run a basic RoLE model.
1. Extract summary statistics from a RolE model, plot them, and relate the visuals to ecological/evolutionary processes.
1. Save RoLE models to disk.

## Planned exercises

* Installation
* TL;DR Run your first simulations
* Getting started with roleR
* Creating a roleParams object and setting model parameters
* Run simulations using the new roleParams
* Inspect the output of the simulation runs
* Setting prior ranges on parameters
* Experimentation time (set a challenge and report back?)

### Installing roleR
:::(.callout-note}
You do not need to install roleR for this workshop, rather this is here for
completeness and future information should you wish to install RoLE on your home cluster.
:::

roleR is currently installed directly from the github repository using the
`remotes::github_install()` function.

```r
> install.packages("remotes")
> library(remotes)
> remotes::install_github('role-model/roleR')
```

## Supporting materials

_Describe, and where possible link to, lesson materials that will be needed for this section of the workshop. These could include code for live coding, code documentation, book chapters, videos/animations, etc._

_For bonus points organize these according to whether they already exist or we need to create them!_

### Extant

### To create

* Relevant chapters of user guide.

## Key points

_List 1-3 key takeaways from this section of the workshop._
