# Theory and motivation of process modeling

## Key questions

1. What is a process modeling approach?
1. What kinds of questions can process models explore (that other methods cannot)?
1. What are the limitations or constraints of process modeling?

## Lesson objectives

After this lesson, learners should be able to...

1. Describe what defines a process model.
1. Evaluate the pros and cons of a process modeling approach.
1. Generate questions in ecology and evolution that could be addressed using process modeling.

## Planned exercises

_List planned activities for this section of the workshop. Examples could include (but not limited to) lectures, live-coding demos, breakout sessions, group discussions, etc._

## Supporting materials

_Describe, and where possible link to, lesson materials that will be needed for this section of the workshop. These could include code for live coding, code documentation, book chapters, videos/animations, etc._

_For bonus points organize these according to whether they already exist or we need to create them!_

### Extant

### To create

## Key points

_List 1-3 key takeaways from this section of the workshop._